### ISSUE TITLE
Not working with Python3.9

### ISSUE THREAD

**Issue by bzh2610** [pafechet/SousMarin#1]
I try to launch the game but I get : 

`  File "/Users/evanollivier/Downloads/SousMarin-master/main.py", line 19
    print 'TESTS'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('TESTS')?
`

Could you help ?

**Comment by pafechet** [comment]
Hi,

Yeah probably, I guess it was supposed to work on Python 2 not future versions such as 3.X.
